import { UserRole } from '@prisma/client';

export const DUMMY_USERS: DUMMY_USERS_TYPE[] = [
  {
    name: 'Katerine Huggens',
    email: 'khuggens0@google.com.au',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/1.png',
  },
  {
    name: 'Millicent Pennicott',
    email: 'mpennicott1@cargocollective.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/2.png',
  },
  {
    name: 'Deb Cranke',
    email: 'dcranke2@bizjournals.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/3.png',
  },
  {
    name: 'Cobb Hazeldean',
    email: 'chazeldean3@edublogs.org',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/4.png',
  },
  {
    name: 'Paco Lea',
    email: 'plea4@livejournal.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/5.png',
  },
  {
    name: 'Kial Langstone',
    email: 'klangstone5@marketwatch.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/6.png',
  },
  {
    name: 'Llywellyn Lewins',
    email: 'llewins6@posterous.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/7.png',
  },
  {
    name: 'Alexandros Sudron',
    email: 'asudron7@admin.ch',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/8.png',
  },
  {
    name: 'Imelda Halso',
    email: 'ihalso8@dyndns.org',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/9.png',
  },
  {
    name: 'Cullen Gliddon',
    email: 'cgliddon9@techcrunch.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/10.png',
  },
  {
    name: 'Dode Hirjak',
    email: 'dhirjaka@xrea.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png',
  },
  {
    name: 'Aarika Lipyeat',
    email: 'alipyeatb@cnet.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/12.png',
  },
  {
    name: 'Elmore Graveson',
    email: 'egravesonc@utexas.edu',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/13.png',
  },
  {
    name: 'Lin Redwin',
    email: 'lredwind@technorati.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/14.png',
  },
  {
    name: 'Seumas Tales',
    email: 'stalese@networksolutions.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/15.png',
  },
  {
    name: 'Christina Newton',
    email: 'cnewtonf@google.co.uk',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/16.png',
  },
  {
    name: 'Dilan Corcut',
    email: 'dcorcutg@seesaa.net',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/17.png',
  },
  {
    name: 'Lia Danielkiewicz',
    email: 'ldanielkiewiczh@irs.gov',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/18.png',
  },
  {
    name: 'Jasmin Sealand',
    email: 'jsealandi@freewebs.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/19.png',
  },
  {
    name: 'Kean Wickins',
    email: 'kwickinsj@newsvine.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/20.png',
  },
  {
    name: 'Marian Justun',
    email: 'mjustunk@tiny.cc',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/21.png',
  },
  {
    name: 'Isidoro Eaves',
    email: 'ieavesl@mlb.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/22.png',
  },
  {
    name: 'Fidelio Minard',
    email: 'fminardm@nifty.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/23.png',
  },
  {
    name: 'Bette-ann Albrook',
    email: 'balbrookn@merriam-webster.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/24.png',
  },
  {
    name: 'Cordy Clamp',
    email: 'cclampo@miibeian.gov.cn',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/25.png',
  },
  {
    name: 'Gwenora Boother',
    email: 'gbootherp@sogou.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/26.png',
  },
  {
    name: 'Maurizio Willingham',
    email: 'mwillinghamq@army.mil',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/27.png',
  },
  {
    name: 'Margette Bickley',
    email: 'mbickleyr@webnode.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/28.png',
  },
  {
    name: 'Gunter Heys',
    email: 'gheyss@twitter.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/29.png',
  },
  {
    name: 'Giacopo Jeune',
    email: 'gjeunet@theguardian.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/30.png',
  },
  {
    name: 'Gunther Dametti',
    email: 'gdamettiu@people.com.cn',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/31.png',
  },
  {
    name: 'Edi Cockayne',
    email: 'ecockaynev@ted.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/32.png',
  },
  {
    name: 'Hartley Ringrose',
    email: 'hringrosew@webmd.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/33.png',
  },
  {
    name: 'Joeann Erni',
    email: 'jernix@google.nl',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/34.png',
  },
  {
    name: 'Lavinia Luisetti',
    email: 'lluisettiy@xing.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/35.png',
  },
  {
    name: 'Avigdor Bloggett',
    email: 'abloggettz@tripadvisor.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/36.png',
  },
  {
    name: 'Benito Looney',
    email: 'blooney10@artisteer.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/37.png',
  },
  {
    name: 'Yurik Duck',
    email: 'yduck11@usa.gov',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/38.png',
  },
  {
    name: 'Barnabas Pearce',
    email: 'bpearce12@123-reg.co.uk',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/39.png',
  },
  {
    name: 'Zora Cahn',
    email: 'zcahn13@kickstarter.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/40.png',
  },
  {
    name: 'Karie Brodeur',
    email: 'kbrodeur14@odnoklassniki.ru',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/41.png',
  },
  {
    name: 'Bartlett Mackett',
    email: 'bmackett15@epa.gov',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/42.png',
  },
  {
    name: 'Filberte Farrent',
    email: 'ffarrent16@usa.gov',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/43.png',
  },
  {
    name: 'Jack Poles',
    email: 'jpoles17@shop-pro.jp',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/44.png',
  },
  {
    name: 'Natala Elrick',
    email: 'nelrick18@businessinsider.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/45.png',
  },
  {
    name: 'Sean Bellin',
    email: 'sbellin19@utexas.edu',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/46.png',
  },
  {
    name: 'Idaline Schimann',
    email: 'ischimann1a@csmonitor.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/47.png',
  },
  {
    name: 'Amanda Seaman',
    email: 'aseaman1b@livejournal.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/48.png',
  },
  {
    name: 'Lane Mendes',
    email: 'lmendes1c@sfgate.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/49.png',
  },
  {
    name: 'Marcus Neely',
    email: 'mneely1d@mapy.cz',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/50.png',
  },
  {
    name: 'Garv Hymer',
    email: 'ghymer1e@mayoclinic.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/51.png',
  },
  {
    name: 'Teodor Spary',
    email: 'tspary1f@senate.gov',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/52.png',
  },
  {
    name: 'Huey Nelius',
    email: 'hnelius1g@wisc.edu',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/53.png',
  },
  {
    name: 'Anatol Masic',
    email: 'amasic1h@usgs.gov',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/54.png',
  },
  {
    name: 'Jinny McGuff',
    email: 'jmcguff1i@prnewswire.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/55.png',
  },
  {
    name: 'Charlotta Astlet',
    email: 'castlet1j@google.it',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/56.png',
  },
  {
    name: 'Wanda Dannell',
    email: 'wdannell1k@privacy.gov.au',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/57.png',
  },
  {
    name: 'Meghan Kasting',
    email: 'mkasting1l@t.co',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/58.png',
  },
  {
    name: 'Wilma Gilyott',
    email: 'wgilyott1m@cnn.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/59.png',
  },
  {
    name: 'Reuven Warrior',
    email: 'rwarrior1n@ucoz.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/60.png',
  },
  {
    name: 'Germain Neles',
    email: 'gneles1o@storify.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/61.png',
  },
  {
    name: 'Therese Edon',
    email: 'tedon1p@senate.gov',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/62.png',
  },
  {
    name: "Berrie O'Longain",
    email: 'bolongain1q@xing.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/63.png',
  },
  {
    name: 'Maia Chason',
    email: 'mchason1r@techcrunch.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/64.png',
  },
  {
    name: 'Fionnula Morhall',
    email: 'fmorhall1s@redcross.org',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/65.png',
  },
  {
    name: 'Culley Oxlee',
    email: 'coxlee1t@ovh.net',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/66.png',
  },
  {
    name: 'Aurilia Daffern',
    email: 'adaffern1u@ehow.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/67.png',
  },
  {
    name: 'Giusto Silkstone',
    email: 'gsilkstone1v@miitbeian.gov.cn',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/68.png',
  },
  {
    name: 'Cristian Gander',
    email: 'cgander1w@multiply.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/69.png',
  },
  {
    name: 'Erminie Strevens',
    email: 'estrevens1x@reuters.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/70.png',
  },
  {
    name: 'Vern Manske',
    email: 'vmanske1y@diigo.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/71.png',
  },
  {
    name: 'Consalve Czajkowski',
    email: 'cczajkowski1z@facebook.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/72.png',
  },
  {
    name: 'May Grinin',
    email: 'mgrinin20@imgur.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/73.png',
  },
  {
    name: 'Hanni Buglar',
    email: 'hbuglar21@barnesandnoble.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/74.png',
  },
  {
    name: 'Hedy Corinton',
    email: 'hcorinton22@forbes.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/75.png',
  },
  {
    name: 'Julienne Battersby',
    email: 'jbattersby23@discovery.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/76.png',
  },
  {
    name: 'Kit Manby',
    email: 'kmanby24@cbsnews.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/77.png',
  },
  {
    name: 'Layne Belloch',
    email: 'lbelloch25@shareasale.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/78.png',
  },
  {
    name: 'Cissiee Beharrell',
    email: 'cbeharrell26@earthlink.net',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/79.png',
  },
  {
    name: 'Tye Du Plantier',
    email: 'tdu27@ocn.ne.jp',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/80.png',
  },
  {
    name: 'Bartholemy Newvill',
    email: 'bnewvill28@buzzfeed.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/81.png',
  },
  {
    name: 'Yuma Thridgould',
    email: 'ythridgould29@blinklist.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/82.png',
  },
  {
    name: 'Trever Swiffin',
    email: 'tswiffin2a@g.co',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/83.png',
  },
  {
    name: 'Sheffy Pattle',
    email: 'spattle2b@time.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/84.png',
  },
  {
    name: 'Bret Romand',
    email: 'bromand2c@tamu.edu',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/85.png',
  },
  {
    name: 'Jed Dovydenas',
    email: 'jdovydenas2d@tmall.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/86.png',
  },
  {
    name: 'Orville Costerd',
    email: 'ocosterd2e@yale.edu',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/87.png',
  },
  {
    name: 'Olin Sheber',
    email: 'osheber2f@eventbrite.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/88.png',
  },
  {
    name: 'Klemens Morrilly',
    email: 'kmorrilly2g@hc360.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/89.png',
  },
  {
    name: 'Junia Karran',
    email: 'jkarran2h@bing.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/90.png',
  },
  {
    name: 'Humfrid Vigurs',
    email: 'hvigurs2i@phoca.cz',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/91.png',
  },
  {
    name: 'Wendel Kippax',
    email: 'wkippax2j@shinystat.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/92.png',
  },
  {
    name: 'Camellia Wheble',
    email: 'cwheble2k@ucla.edu',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/93.png',
  },
  {
    name: 'Shurlock Rushman',
    email: 'srushman2l@dedecms.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/94.png',
  },
  {
    name: 'Gates Harbord',
    email: 'gharbord2m@wikipedia.org',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/95.png',
  },
  {
    name: 'Shane Vogelein',
    email: 'svogelein2n@goo.ne.jp',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/96.png',
  },
  {
    name: 'Erhart Tressler',
    email: 'etressler2o@homestead.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/97.png',
  },
  {
    name: 'Spence Allum',
    email: 'sallum2p@usatoday.com',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/98.png',
  },
  {
    name: 'Karlotte Harriot',
    email: 'kharriot2q@clickbank.net',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/99.png',
  },
  {
    name: 'Terrence Bellenger',
    email: 'tbellenger2r@miibeian.gov.cn',
    role: 'CUSTOMER',
    image: 'https://d2u8k2ocievbld.cloudfront.net/memojis/male/100.png',
  },
];

type DUMMY_USERS_TYPE = {
  name: string;
  email: string;
  role: UserRole;
  image: string;
};
